# theme = "dracula"
theme = "dark_transparent"

[editor]
# line-number = "relative" # 相对行号
mouse = true
bufferline = "multiple"
color-modes = true
cursorline = true

# [editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"

# [editor.indent-guides]
# render = true

# [editor.whitespace.render]
# space = "none"
# tab = "all"

# [editor.statusline]
# left = ["mode", "spinner", "file-name"]
# center = []
# right = ["diagnostics", "selections", "position", "file-encoding"]

[keys.insert]
{{- if eq .chezmoi.os "windows" }}
# 退出插入模式关闭输入法,必须有im-switch-for-windows
# https://github.com/fengwk/im-switch-for-windows
esc = ["normal_mode", ':pipe-to cmd /c im-switch-x64.exe en']
{{- else }}
esc = ["normal_mode", ":sh fcitx5-remote -c"] # 退出插入模式后关闭输入法
{{- end }}

[keys.normal]
# 保险在normal模式下按esc也退出输入法
{{- if eq .chezmoi.os "windows" }}
# esc = ["normal_mode", ':pipe-to cmd /c im-switch-x64.exe en']
esc = ["normal_mode"]
{{- else }}
esc = ["normal_mode", ':sh fcitx5-remote -c']
":" = ["command_mode", ':sh fcitx5-remote -c']
{{- end }}
